apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfgdfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfgdfg
  template:
    metadata:
      labels:
        app: dfgdfg
    spec:
      containers:
      - image: okteto.dev/dfgdfg:latest
        name: dfgdfg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "eeaa7c61-bed2-4d46-8a22-d1ca6bfc52ca"
        - name: Vless_Path
          value: "/fggh7swrgjyu"
        - name: Vmess_UUID
          value: "eeaa7c61-bed2-4d46-8a22-d1ca6bfc52ca"
        - name: Vmess_Path
          value: "/fdbx26ehtd"
        - name: Share_Path
          value: "/v2link"
